# Generated by Django 5.2.7 on 2025-10-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите полное имя автора', max_length=100, verbose_name='Имя автора')),
                ('birth_date', models.DateField(blank=True, help_text='Введите дату рождения автора', null=True, verbose_name='Дата рождения')),
                ('bio', models.TextField(blank=True, help_text='Введите краткую биографию автора', verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите полное название книги', max_length=200, verbose_name='Название книги')),
                ('published_date', models.DateField(help_text='Введите дату первой публикации книги', verbose_name='Дата публикации')),
                ('isbn', models.CharField(help_text='Введите 13-значный ISBN код', max_length=13, unique=True, verbose_name='ISBN')),
                ('pages', models.IntegerField(help_text='Введите общее количество страниц в книге', verbose_name='Количество страниц')),
                ('author', models.ForeignKey(help_text='Выберите автора книги', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author', verbose_name='Автор книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
    ]
